import AuthProvider from "./components/AuthProvider";
import Nav from "./components/Nav";
import "./globals.css";

import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/ThemeProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

import { Toaster } from "@/components/ui/toaster"


export const metadata = {
  title: "Natalcare Hub",
  description: "Generated by Natalcare Hub",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <meta name="viewport" content="initial-scale=1, width=device-width" />

      <AuthProvider>
        <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
           
            <Nav>{children}</Nav>
            <Toaster />
          </ThemeProvider>
        </body>
      </AuthProvider>

    </html>
  );
}
